apps/storybook/.storybook/main.ts, apps/web/layout/Header.tsx, apps/web/layout/Layout.tsx, apps/web/layout/index.ts, apps/web/package.json, apps/web/pages/_app.tsx, apps/web/pages/index.tsx, package.json, packages/graphql/apollo-client.ts, packages/graphql/eden/codegen.yml, packages/graphql/eden/index.ts, packages/graphql/eden/projects/findProjects.ts, packages/graphql/eden/projects/index.ts, packages/graphql/generated/graphqlEden.ts, packages/graphql/index.ts, packages/graphql/package.json, packages/graphql/tsconfig.json, turbo.json, yarn.lock
adds -  basic graphql connection to eden api
adds -  generated types for eden api
fixes - storybook rendering issue when running `yarn storybook`
=> feat:graphql

README.md, package.json, packages/config/package.json
update readme file and package.json files
=> chore:update readme

apps/web/package.json, packages/ui/src/components/RoleCandidateSelector/RoleCandidateSelector.stories.tsx, packages/ui/src/components/RoleCandidateSelector/RoleCandidateSelector.test.tsx, packages/ui/src/components/RoleCandidateSelector/RoleCandidateSelector.tsx, packages/ui/src/components/RoleCandidateSelector/index.ts, yarn.lock
=> feat: Add RoleCandidateSelector component

packages/ui/package.json, packages/ui/src/cards/UserCard/UserCard.tsx, packages/ui/src/components/CandidateSelectionList/CandidateSelectionList.stories.tsx, packages/ui/src/components/CandidateSelectionList/CandidateSelectionList.test.tsx, packages/ui/src/components/CandidateSelectionList/CandidateSelectionList.tsx, packages/ui/src/components/CandidateSelectionList/index.ts, packages/ui/src/components/RoleCandidateSelector/RoleCandidateSelector.stories.tsx, packages/ui/src/components/RoleCandidateSelector/RoleCandidateSelector.tsx, packages/ui/src/components/index.ts, yarn.lock
=> Feat: CandidateSelectionList component

packages/ui/src/elements/Badge/Badge.stories.tsx, packages/ui/src/elements/Badge/Badge.test.tsx, packages/ui/src/elements/Badge/Badge.tsx, packages/ui/src/elements/Badge/index.ts
Created Badge component with configurable color and text props. [Dework FrontEnd 1250](https://app.dework.xyz/developer-dao/frontend-p?taskId=4ee871f0-eb9b-45b9-b958-1090baaae0e8)
=> Feat: Badge Component

apps/web/pages/404/index.tsx, apps/web/pages/champion-dashboard/recruit/[_id].tsx, packages/graphql/generated/index.ts, packages/graphql/index.ts, packages/ui/src/cards/index.ts, packages/ui/src/components/CandidateSelectionList/CandidateSelectionList.stories.tsx, packages/ui/src/components/CandidateSelectionList/CandidateSelectionList.test.tsx, packages/ui/src/components/CandidateSelectionList/CandidateSelectionList.tsx
brings all graphql querying to the page parent
start of a basic structure for querying data and testing with storybook and jest
=> feat:page querying

packages/ui/src/cards/ProjectCard/ProjectCard.tsx, packages/ui/src/cards/UserCard/UserCard.stories.tsx, packages/ui/src/cards/UserInformationCard/UserInformationCard.stories.tsx, packages/ui/src/cards/UserInformationCard/UserInformationCard.tsx, packages/ui/src/components/CollectionOfUsers/CollectionOfUsers.stories.tsx, packages/ui/src/components/CollectionOfUsers/CollectionOfUsers.test.tsx, packages/ui/src/components/CollectionOfUsers/CollectionOfUsers.tsx, packages/ui/src/components/UserWithDescription/UserWithDescription.stories.tsx, packages/ui/src/elements/Avatar/Avatar.stories.tsx, packages/ui/src/elements/Avatar/Avatar.tsx, packages/ui/src/elements/Badge/Badge.stories.tsx, packages/ui/src/elements/Badge/Badge.test.tsx, packages/ui/src/elements/Badge/Badge.tsx, packages/ui/src/elements/Favorite/Favorite.test.tsx, packages/ui/src/elements/Favorite/Favorite.tsx
a quick sweep through of components and mock data for storybook
=> chore:component cleanup

apps/web/pages/apply/[_id].tsx, apps/web/pages/invites/index.tsx, packages/ui/src/containers/ApplyContainer/ApplyContainer.stories.tsx, packages/ui/src/containers/ApplyContainer/ApplyContainer.test.tsx, packages/ui/src/containers/ApplyContainer/ApplyContainer.tsx, packages/ui/src/containers/ApplyContainer/index.ts, packages/ui/src/containers/index.ts
ApplyContainer with working user apply to project
=> feat:ApplyContainer

apps/web/pages/champion-board/index.tsx, apps/web/pages/champion-board/recruit/[_id].tsx, packages/graphql/eden/project/findProject.ts, packages/ui/src/cards/ProjectCardSmall/ProjectCardSmall.tsx, packages/ui/src/cards/UserCard/UserCard.stories.tsx, packages/ui/src/cards/UserCard/UserCard.tsx, packages/ui/src/containers/ChampionContainer/ChampionContainer.tsx, packages/ui/src/containers/ChampionRecruitContainer/ChampionRecruitContainer.tsx, packages/ui/src/lists/CandidateSelectionList/CandidateSelectionList.tsx, packages/ui/src/lists/SideNavProjectList/SideNavProjectList.tsx
cleaned up types for UserCard
added engaged talent list in champion-board
cleaned project list on champion-board
=> fix:types for UserCard

apps/web/pages/profile/index.tsx, packages/ui/src/cards/SkillsCard/SkillsCard.stories.tsx, packages/ui/src/cards/SkillsCard/SkillsCard.tsx, packages/ui/src/cards/UserInformationCard/UserInformationCard.tsx, packages/ui/src/components/BioComponent/BioComponent.tsx, packages/ui/src/components/Endorsements/Endorsements.stories.tsx, packages/ui/src/containers/ChampionRecruitContainer/ChampionRecruitContainer.tsx, packages/ui/src/containers/ProfileContainer/ProfileContainer.stories.tsx, packages/ui/src/containers/ProfileContainer/ProfileContainer.test.tsx, packages/ui/src/containers/ProfileContainer/ProfileContainer.tsx, packages/ui/src/containers/ProfileContainer/index.ts, packages/ui/src/containers/index.ts, packages/ui/src/elements/Badge/Badge.tsx, packages/ui/src/elements/Card/Card.stories.tsx, packages/ui/src/elements/Dropdown/Dropdown.tsx, packages/ui/src/selectors/EmojiSelector/EmojiSelector.tsx
basic profile page layout set
needs to be wired up for data and functionality
=> feat:profile page

packages/ui/src/components/AvailabilityComp/AvailabilityComp.stories.tsx, packages/ui/src/components/AvailabilityComp/AvailabilityComp.test.tsx, packages/ui/src/components/AvailabilityComp/AvailabilityComp.tsx, packages/ui/src/components/AvailabilityComp/index.ts, packages/ui/src/elements/ProgressBar/ProgressBar.tsx
1. Availability comp
2. https://app.dework.xyz/profile/zorooroo/board?taskId=c52d2d3e-174e-4879-868f-373215280dc2
=> Availability comp

packages/graphql/eden/member/findMember.ts, packages/graphql/generated/graphqlEden.ts, packages/ui/src/cards/ProjectCard/ProjectCard.tsx, packages/ui/src/cards/SkillsCard/SkillsCard.stories.tsx, packages/ui/src/cards/SkillsCard/SkillsCard.tsx, packages/ui/src/components/AvailabilityComp/AvailabilityComp.tsx, packages/ui/src/components/BioComponent/BioComponent.tsx, packages/ui/src/components/SocialMediaComponent/SocialMediaComp.tsx, packages/ui/src/components/index.ts, packages/ui/src/containers/ChampionRecruitContainer/ChampionRecruitContainer.tsx, packages/ui/src/elements/Badge/Badge.stories.tsx, packages/ui/src/elements/Badge/Badge.test.tsx, packages/ui/src/elements/Badge/Badge.tsx
=> chore:clean up recruit container

apps/web/pages/applications/index.tsx, apps/web/pages/champion-board/recruit/[_id].tsx, apps/web/pages/projects/index.tsx, packages/ui/src/containers/ProjectsContainer/ProjectsContainer.tsx
adding filter for favourites
filter for engaged on ApplicationsPage is WIP
=> feat:filter for favourites

apps/web/pages/signup/index.tsx, packages/context/src/SignUpContext/SignUpContext.tsx, packages/context/src/SignUpContext/SignUpProvider.tsx, packages/context/src/SignUpContext/index.ts, packages/context/src/index.ts, packages/graphql/generated/graphqlEden.ts, packages/ui/src/containers/SignUpContainer/SignUpContainer.stories.tsx, packages/ui/src/containers/SignUpContainer/SignUpContainer.tsx, packages/ui/src/containers/SignUpContainer/SignUpViews/SignUpViewBio.tsx, packages/ui/src/containers/SignUpContainer/SignUpViews/SignUpViewConfirm.tsx, packages/ui/src/containers/SignUpContainer/SignUpViews/SignUpViewShare.tsx, packages/ui/src/containers/SignUpContainer/SignUpViews/SignUpViewSkills.tsx, packages/ui/src/containers/SignUpContainer/SignUpViews/SignUpViewSocials.tsx, packages/ui/src/containers/SignUpContainer/SignUpViews/SignUpViewSuccess.tsx, packages/ui/src/containers/SignUpContainer/SignUpViews/SignUpViewXP.tsx, packages/ui/src/containers/SignUpContainer/SignUpViews/index.ts, packages/ui/src/containers/SignUpContainer/index.ts, packages/ui/src/containers/index.ts, packages/ui/src/elements/Button/Button.tsx, packages/ui/src/lists/CandidateSelectionList/CandidateSelectionList.tsx
basic sign up views and context with working mutation and routing
=> feat:basic signup structure

packages/ui/src/cards/UserCard/UserCard.tsx, packages/ui/src/containers/ChampionContainer/ChampionContainer.stories.tsx, packages/ui/src/containers/ChampionContainer/ChampionContainer.tsx, packages/ui/src/containers/ChampionRecruitContainer/ChampionRecruitContainer.stories.tsx, packages/ui/src/containers/ChampionRecruitContainer/ChampionRecruitContainer.tsx, packages/ui/src/containers/ProjectsContainer/ProjectsContainer.stories.tsx, packages/ui/src/containers/SignUpContainer/SignUpContainer.tsx, packages/ui/src/lists/CandidateSelectionList/CandidateSelectionList.stories.tsx, packages/ui/src/lists/CandidateSelectionList/CandidateSelectionList.tsx, packages/ui/src/selectors/RoleCandidateSelector/RoleCandidateSelector.tsx
clean up stories for:
ChampionContainer
ChampionRecruitContainer
ProjectsContainer
CandidateSelectionList
=> chore:clean up stories

packages/context/src/SignUpContext/SignUpContext.tsx, packages/context/src/SignUpContext/SignUpProvider.tsx, packages/graphql/eden/member/findMemberFull.ts, packages/ui/constants.ts, packages/ui/src/containers/SignUpContainer/SignUpContainer.tsx, packages/ui/src/containers/SignUpContainer/SignUpViews/SignUpViewBio.tsx, packages/ui/src/containers/SignUpContainer/SignUpViews/SignUpViewConfirm.tsx, packages/ui/src/containers/SignUpContainer/SignUpViews/SignUpViewShare.tsx, packages/ui/src/containers/SignUpContainer/SignUpViews/SignUpViewSkills.tsx, packages/ui/src/containers/SignUpContainer/SignUpViews/SignUpViewSocials.tsx, packages/ui/src/containers/SignUpContainer/SignUpViews/SignUpViewXP.tsx, packages/ui/src/elements/Dropdown/Dropdown.tsx, packages/ui/src/elements/TextField/TextField.tsx, packages/ui/src/lists/CandidateSelectionList/CandidateSelectionList.tsx
improved sign up flow, added inputs for:
timezone
hour per week
projects proud of
work showcase
=> feat:improving sign up flow

apps/web/pages/launch/index.tsx, packages/ui/src/containers/LaunchContainer/LaunchContainer.tsx, packages/ui/src/containers/LaunchContainer/LaunchViews/LaunchViewDescribe.tsx, packages/ui/src/containers/LaunchContainer/LaunchViews/LaunchViewLinks.tsx, packages/ui/src/containers/LaunchContainer/LaunchViews/LaunchViewName.tsx, packages/ui/src/containers/LaunchContainer/LaunchViews/LaunchViewRoles.tsx, packages/ui/src/containers/LaunchContainer/LaunchViews/LaunchViewSteps.tsx, packages/ui/src/containers/LaunchContainer/LaunchViews/LaunchViewVerify.tsx, packages/ui/src/elements/Dropdown/Dropdown.tsx, packages/ui/src/selectors/SkillSelector/SkillSelector.tsx
set up basic query for launch page
added titles
=> feat:basic query for launch

packages/ui/src/elements/TextAreaComponent/TextArea.stories.tsx, packages/ui/src/elements/TextAreaComponent/TextArea.test.tsx, packages/ui/src/elements/TextAreaComponent/TextArea.tsx, packages/ui/src/elements/TextAreaComponent/index.ts
=> feat: text area

apps/storybook/.storybook/decorator.tsx, apps/storybook/mocks/MemberMock.ts, apps/storybook/mocks/index.ts, packages/context/src/SignUpContext/SignUpContext.tsx, packages/context/src/SignUpContext/SignUpProvider.tsx, packages/graphql/generated/graphqlEden.ts, packages/ui/src/components/AvailabilityComp/AvailabilityComp.tsx, packages/ui/src/components/BioComponent/BioComponent.tsx, packages/ui/src/components/SocialMediaComponent/SocialMediaComp.stories.tsx, packages/ui/src/components/SocialMediaComponent/SocialMediaComp.tsx, packages/ui/src/components/UserProfileMenu/UserProfileMenu.tsx, packages/ui/src/containers/ChampionRecruitContainer/ChampionRecruitContainer.tsx, packages/ui/src/containers/ProfileContainer/ProfileContainer.stories.tsx, packages/ui/src/containers/ProfileContainer/ProfileContainer.tsx, packages/ui/src/containers/SignUpContainer/SignUpContainer.tsx, packages/ui/src/containers/SignUpContainer/SignUpViews/SignUpViewSocials.tsx, packages/ui/src/lists/CandidateSelectionList/CandidateSelectionList.tsx
allows user to add social links
mock user data setup for storybook
=> feat:working profile links

apps/web/pages/onboard/party/[partyId].tsx, packages/graphql/eden/member/index.ts, packages/graphql/eden/member/updateMember.ts, packages/ui/src/selectors/SkillSelector/SkillSelector.tsx
Replace addSkillToMember with updateMember
I also triggered onSetSkills callback when a skill is deleted on selector component
=> Replace addSkillToMember with updateMember

apps/web/package.json, apps/web/pages/champion-board/recruit/[_id].tsx, apps/web/pages/index.tsx, packages/config/package.json, packages/config/tailwind.config.js, packages/ui/src/components/AvailabilityComp/AvailabilityComp.tsx, packages/ui/src/components/FormStepper/FormStepper.tsx, packages/ui/src/components/FormStepper/styles.css, packages/ui/src/containers/ChampionContainer/ChampionContainer.tsx, packages/ui/src/containers/ChampionRecruitContainer/ChampionRecruitContainer.stories.tsx, packages/ui/src/containers/ChampionRecruitContainer/ChampionRecruitContainer.test.tsx, packages/ui/src/containers/ChampionRecruitContainer/ChampionRecruitContainer.tsx, packages/ui/src/containers/LaunchContainer/LaunchContainer.tsx, packages/ui/src/containers/ProfileContainer/ProfileContainer.tsx, packages/ui/src/containers/ProjectsContainer/ProjectsContainer.tsx, packages/ui/src/containers/SignUpContainer/SignUpContainer.tsx, packages/ui/src/lists/CandidateSelectionList/CandidateSelectionList.tsx, packages/ui/src/lists/RecommendedList/RecommendedList.tsx, packages/ui/src/lists/SideNavProjectList/SideNavProjectList.tsx, yarn.lock
adds working shortlisted and rejected from champion-board/recruit
removed scrollbar
=> feat:shortlist-reject-mutations

packages/ui/src/cards/ProjectActivityCard/ProjectActivityCard.stories.tsx, packages/ui/src/cards/ProjectActivityCard/ProjectActivityCard.test.tsx, packages/ui/src/cards/ProjectActivityCard/ProjectActivityCard.tsx, packages/ui/src/cards/ProjectActivityCard/index.ts
1> Feat: project activity card
=> Feat: project activity card

apps/web/pages/applications/index.tsx, apps/web/pages/champion-board/recruit/[_id].tsx, apps/web/pages/invites/index.tsx, apps/web/pages/my-projects/index.tsx, apps/web/pages/profile/index.tsx, apps/web/pages/projects/[projectId]/index.tsx, apps/web/pages/projects/index.tsx, packages/context/src/UserContext/UserProvider.tsx, packages/graphql/eden/member/findMemberFull.ts, packages/graphql/eden/member/index.ts, packages/graphql/eden/member/memberSubscription.ts, packages/ui/src/cards/ProjectCardSmall/ProjectCardSmall.tsx, packages/ui/src/components/UserProfileMenu/UserProfileMenu.stories.tsx, packages/ui/src/components/UserProfileMenu/UserProfileMenu.tsx, packages/ui/src/containers/SignUpContainer/SignUpContainer.tsx, packages/ui/src/lists/ProjectList/ProjectList.tsx, packages/ui/src/lists/SideNavProjectList/SideNavProjectList.tsx
adds: 
subscription to user
filtering for user dashboard
=> feat:subscription on user

apps/web/pages/onboard/party/[partyId].tsx, packages/graphql/eden/member/memberSubscription.ts, packages/graphql/eden/room/roomUpdated.ts, packages/ui/src/cards/EditProfileOnboardPartyCard/EditProfileOnboardPartyCard.stories.tsx, packages/ui/src/cards/EditProfileOnboardPartyCard/EditProfileOnboardPartyCard.test.tsx, packages/ui/src/cards/EditProfileOnboardPartyCard/EditProfileOnboardPartyCard.tsx, packages/ui/src/cards/EditProfileOnboardPartyCard/index.ts, packages/ui/src/cards/UserCardOnboardParty/UserCardOnboardParty.stories.tsx, packages/ui/src/cards/UserCardOnboardParty/UserCardOnboardParty.test.tsx, packages/ui/src/cards/UserCardOnboardParty/UserCardOnboardParty.tsx, packages/ui/src/cards/UserCardOnboardParty/index.ts, packages/ui/src/cards/index.ts, packages/ui/src/containers/OnboardPartyContainer/OnboardPartyContainer.stories.tsx, packages/ui/src/containers/OnboardPartyContainer/OnboardPartyContainer.test.tsx, packages/ui/src/containers/OnboardPartyContainer/OnboardPartyContainer.tsx, packages/ui/src/containers/OnboardPartyContainer/index.ts, packages/ui/src/containers/index.ts
Remove all data from room subscription that is not members id
Abstract All parts of Onboard Party page into components
=> More party page optimization 

packages/ui/src/components/FormStepper/FormStepper.stories.tsx, packages/ui/src/components/FormStepper/FormStepper.test.tsx, packages/ui/src/components/FormStepper/FormStepper.tsx, packages/ui/src/containers/LaunchContainer/LaunchContainer.tsx, packages/ui/src/containers/SignUpContainer/SignUpContainer.tsx
=> Fix: Improve style of progress bar

apps/web/pages/_app.tsx, apps/web/pages/_document.tsx, apps/web/pages/applications/index.tsx, apps/web/pages/apply/[_id].tsx, apps/web/pages/champion-board/[_id]/index.tsx, apps/web/pages/champion-board/index.tsx, apps/web/pages/champion-board/recruit/[_id].tsx, apps/web/pages/index.tsx, apps/web/pages/invites/index.tsx, apps/web/pages/launch/index.tsx, apps/web/pages/login/index.tsx, apps/web/pages/my-projects/index.tsx, apps/web/pages/onboard/party/[partyId].tsx, apps/web/pages/profile/index.tsx, apps/web/pages/projects/[projectId]/index.tsx, apps/web/pages/projects/index.tsx, apps/web/pages/signup/index.tsx, packages/context/src/SignUpContext/SignUpProvider.tsx, packages/graphql/eden/member/findMemberFull.ts, packages/graphql/eden/member/memberSubscription.ts, packages/graphql/generated/graphqlEden.ts, packages/ui/src/containers/SignUpContainer/SignUpContainer.tsx, packages/ui/src/containers/SignUpContainer/SignUpViews/SignUpViewBio.tsx, packages/ui/src/layout/AppPublicLayout/AppPublicLayout.tsx, packages/ui/src/layout/AppPublicLayout/index.ts, packages/ui/src/layout/AppUserLayout/AppUserLayout.tsx, packages/ui/src/layout/AppUserLayout/index.ts, packages/ui/src/layout/AppUserMenuLayout/AppUserMenuLayout.tsx, packages/ui/src/layout/AppUserMenuLayout/index.ts, packages/ui/src/layout/index.ts
this PR sets up basic redirect to login if user isn't logged in.
also basic layouts
=> feat:app page authentication

apps/web/pages/applications/index.tsx, apps/web/pages/invites/index.tsx, apps/web/pages/my-projects/[_id]/index.tsx, apps/web/pages/my-projects/index.tsx, apps/web/pages/profile/index.tsx, packages/ui/src/cards/ProjectCard/ProjectCard.tsx, packages/ui/src/components/ProjectInfo/ProjectInfo.stories.tsx, packages/ui/src/components/ProjectInfo/ProjectInfo.tsx, packages/ui/src/components/index.ts, packages/ui/src/containers/MyProjectContainer/MyProjectContainer.stories.tsx, packages/ui/src/containers/MyProjectContainer/MyProjectContainer.test.tsx, packages/ui/src/containers/MyProjectContainer/MyProjectContainer.tsx, packages/ui/src/containers/MyProjectContainer/index.ts, packages/ui/src/containers/ProfileContainer/ProfileContainer.tsx, packages/ui/src/containers/index.ts, packages/ui/src/layout/AppUserMenuLayout/AppUserMenuLayout.tsx, packages/ui/src/lists/ProjectList/ProjectList.tsx
set up my-project/[id] page
basic MyProjectContainer files in place
clean up ui on profile page.  still needs mutation and textareas
added number of in various project pages
=> chore:clean up various ui

apps/web/pages/invites/[_id]/index.tsx, apps/web/pages/invites/index.tsx, packages/ui/src/cards/ProjectCard/ProjectCard.tsx, packages/ui/src/containers/InviteContainer/InviteContainer.stories.tsx, packages/ui/src/containers/InviteContainer/InviteContainer.test.tsx, packages/ui/src/containers/InviteContainer/InviteContainer.tsx, packages/ui/src/containers/InviteContainer/index.ts, packages/ui/src/containers/index.ts, packages/ui/src/lists/ProjectList/ProjectList.tsx
adds InviteContainer
working mutation to accept invite and redirected to my-projects/[_id]
=> feat:basic functional InviteContainer

apps/storybook/mocks/data/findRoleTemplates.ts, apps/storybook/mocks/data/index.ts, apps/storybook/mocks/index.ts, apps/web/pages/signup/test-page.tsx, packages/ui/src/cards/SignUpCard/SignUpCard.stories.tsx, packages/ui/src/cards/SignUpCard/SignUpCard.test.tsx, packages/ui/src/cards/SignUpCard/SignUpCard.tsx, packages/ui/src/cards/SignUpCard/index.ts, packages/ui/src/cards/UserProfileCard/UserProfileCard.stories.tsx, packages/ui/src/cards/UserProfileCard/UserProfileCard.test.tsx, packages/ui/src/cards/UserProfileCard/UserProfileCard.tsx, packages/ui/src/cards/index.ts, packages/ui/src/selectors/RoleSelector/RoleSelector.stories.tsx, packages/ui/src/selectors/RoleSelector/RoleSelector.test.tsx, packages/ui/src/selectors/RoleSelector/RoleSelector.tsx, packages/ui/src/selectors/RoleSelector/index.ts, packages/ui/src/selectors/index.ts
adds RoleSelector
start of test page for new user flow
start of SignUpCard for new user flow
=> feat:role-selector

apps/storybook/mocks/ProjectMock.ts, apps/web/pages/signup/test-page.tsx, packages/ui/src/cards/ProjectMatchCard/ProjectMatchCard.stories.tsx, packages/ui/src/cards/ProjectMatchCard/ProjectMatchCard.test.tsx, packages/ui/src/cards/ProjectMatchCard/ProjectMatchCard.tsx, packages/ui/src/cards/ProjectMatchCard/index.ts, packages/ui/src/cards/index.ts, packages/ui/src/components/ProjectChampion/ProjectChampion.stories.tsx, packages/ui/src/components/ProjectChampion/ProjectChampion.test.tsx, packages/ui/src/components/ProjectChampion/ProjectChampion.tsx, packages/ui/src/components/index.ts, packages/ui/src/lists/ProjectMatchList/ProjectMatchList.stories.tsx, packages/ui/src/lists/ProjectMatchList/ProjectMatchList.test.tsx, packages/ui/src/lists/ProjectMatchList/ProjectMatchList.tsx, packages/ui/src/lists/ProjectMatchList/index.ts, packages/ui/src/lists/index.ts
adds ProjectMatchCard and ProjectMatchList
=> feat:project-match-card-and-list

packages/ui/src/cards/SignUpCard/SignUpCard.tsx, packages/ui/src/cards/SocialMediaProfileCard/SocialMediaProfileCard.stories.tsx, packages/ui/src/cards/SocialMediaProfileCard/SocialMediaProfileCard.test.tsx, packages/ui/src/cards/SocialMediaProfileCard/SocialMediaProfileCard.tsx, packages/ui/src/cards/SocialMediaProfileCard/index.ts
Feat: Social Media Profile Card
=> Feat: SocialMediaProfileCard

apps/alpha/pages/champion-board/recruit/[_id].tsx, packages/ui/src/cards/ProjectEditSelectorCard/ProjectEditSelectorCard.tsx, packages/ui/src/containers/ChampionMatchContainer/ChampionMatchContainer.tsx, packages/ui/src/containers/ShortlistContainer/ShortlistContainer.tsx
Remove cards — done
Remove extra props I.e - projects singular — done
Add frontend side box filter —match  — done
member skills query — on selection role
Add paginations — done
Make cards selectable — done
Add key for props — done
Add more button onClick — done
Add Go Back Button to route to champion board page -- done
=> Feat/champion board/recruit

apps/alpha/pages/launch/shortlist/index.tsx, apps/alpha/pages/test/hackathon/index.tsx, packages/context/src/HackathonContext/HackathonContext.tsx, packages/context/src/HackathonContext/HackathonProvider.tsx, packages/context/src/HackathonContext/index.ts, packages/context/src/index.ts, packages/ui/src/cards/SignUpRoleSelectCard/SignUpRoleSelectCard.tsx, packages/ui/src/cards/StaticCard/StaticCard.tsx, packages/ui/src/cards/user/UserProfileCard/UserProfileCard.tsx, packages/ui/src/containers/ApplyByRoleContainer/ApplyByRoleContainer.tsx, packages/ui/src/containers/ShortlistContainer/ShortlistContainer.tsx, packages/ui/src/containers/SignUpContainerSide/SignUpContainerSide.tsx, packages/ui/src/containers/index.ts, packages/ui/src/containers/test/HackathonModalContainer/HackathonModalContainer.stories.tsx, packages/ui/src/containers/test/HackathonModalContainer/HackathonModalContainer.test.tsx, packages/ui/src/containers/test/HackathonModalContainer/HackathonModalContainer.tsx, packages/ui/src/containers/test/HackathonModalContainer/index.ts, packages/ui/src/lists/ProjectMatchList/ProjectMatchList.tsx, packages/ui/src/modals/FindTalentModal/FindTalentModal.tsx, packages/ui/src/modals/ReviewModal/ReviewModal.tsx, packages/ui/src/selectors/BadgeSelector/BadgeSelector.tsx
added a new provider and context for `/test/hackathon` page called HackathonContext and HackathonProvider
also a HackathonModalContainer
can be used for `/test/projects` and `/test/user` pages but haven't put in yet
=> new context for test pages

packages/ui/src/cards/StaticCard/StaticCard.tsx, packages/ui/src/elements/Button/Button.tsx, packages/ui/src/elements/LongText/LongText.stories.tsx, packages/ui/src/elements/LongText/LongText.test.tsx, packages/ui/src/elements/LongText/LongText.tsx, packages/ui/src/elements/LongText/index.ts, packages/ui/src/elements/index.ts
https://www.figma.com/file/fqoE42V9NeQmGPcBl2j7JR/Everything-Together?node-id=466%3A1757
=> Changed Static Card UI to be matched with Figma

apps/alpha/pages/api/discord/createDM.ts, apps/alpha/pages/chat/testdm/index.tsx, apps/alpha/types/type.ts, packages/ui/types/type.ts
I add a DIscord DM API for the frontend, go to check `api/discord/createDM`. The loigc is that I create a DM channel first(No permission checking here, no matter whether you open your DM, you will always get this channel. Encounter an error until you send messages to this DM channel), then send a message to this DM channel (Works like Send msg to normal channels). 
@e-roy waxy, I also gave an update to `packages/ui/types/type.ts`. Thanks for your elements!
=> DM Api integration

packages/ui/src/elements/SelectBox/SelectBox.test.tsx
This PR is the result of @sbelka-1703 running into issues with testing `FindTalentDropdownModal`. 
It took a bit to figure out how to select options with this setup and there's some goofiness to how this component works, which we'll document and then possibly figure out how to refactor later.
=> add tests for `SelectBox`

apps/alpha/pages/fill-profile/index.tsx, apps/nodes/pages/onboard/party/[partyId].tsx, packages/ui/src/cards/MemberMatchCard/MemberMatchCard.tsx, packages/ui/src/cards/MemberProfileCard/MemberProfileCard.tsx, packages/ui/src/cards/StaticCard/StaticCard.tsx, packages/ui/src/cards/user/UserCardOnboardParty/UserCardOnboardParty.tsx, packages/ui/src/cards/user/UserCardOnboardPartyNodes/UserCardOnboardPartyNodes.tsx, packages/ui/src/cards/user/UserDiscoverCard/UserDiscoverCard.tsx, packages/ui/src/cards/user/UserMiniCard/UserMiniCard.tsx, packages/ui/src/cards/user/UsersToMeetCard/UsersToMeetCard.test.tsx, packages/ui/src/cards/user/UsersToMeetCard/UsersToMeetCard.tsx, packages/ui/src/components/SocialMediaComponent/SocialMediaComp.tsx, packages/ui/src/containers/ViewUserProfileContainer/ViewUserProfileContainer.tsx, packages/ui/src/elements/Avatar/Avatar.tsx, packages/ui/src/elements/LevelAvatar/LevelAvatar.tsx, packages/ui/src/elements/MatchAvatar/MatchAvatar.tsx, packages/ui/src/lists/RoleList/RoleList.tsx, packages/ui/src/modals/ProfileExpandedModal/ProfileExpandedModal.tsx, packages/ui/src/modals/StaticModal/StaticModal.tsx
size variants for:
MatchAvatar 
LevelAvatar 
SocialMediaComp
=> size varients for MatchAvatar LevelAvatar and SMC

apps/nodes/pages/grants/index.tsx, apps/nodes/pages/projects/index.tsx, packages/graphql/eden/project/index.ts, packages/graphql/eden/project/matchNodesToProjectRoles.ts, packages/mock/src/graphqlMocks/index.ts, packages/mock/src/graphqlMocks/matchNodesToProjectRolesMock.ts, packages/ui/src/cards/OpenPositionCard/OpenPositionCard.tsx, packages/ui/src/cards/project/ProjectNodeMatchCard/ProjectNodeMatchCard.stories.tsx, packages/ui/src/cards/project/ProjectNodeMatchCard/ProjectNodeMatchCard.test.tsx, packages/ui/src/cards/project/ProjectNodeMatchCard/ProjectNodeMatchCard.tsx, packages/ui/src/cards/project/ProjectNodeMatchCard/index.ts, packages/ui/src/cards/project/index.ts, packages/ui/src/components/OpenPositions/OpenPositions.stories.tsx, packages/ui/src/components/OpenPositions/OpenPositions.tsx, packages/ui/src/containers/FillUserProfileContainer/FillUserProfileContainer.tsx, packages/ui/src/info/ProjectNodeMatchInfo/ProjectNodeMatchInfo.stories.tsx, packages/ui/src/info/ProjectNodeMatchInfo/ProjectNodeMatchInfo.test.tsx, packages/ui/src/info/ProjectNodeMatchInfo/ProjectNodeMatchInfo.tsx, packages/ui/src/info/ProjectNodeMatchInfo/index.ts, packages/ui/src/info/index.ts, packages/ui/src/modals/ProjectModal/ProjectModal.stories.tsx, packages/ui/src/modals/ProjectModal/ProjectModal.test.tsx, packages/ui/src/modals/ProjectModal/ProjectModal.tsx, packages/ui/src/modals/ProjectModal/index.ts, packages/ui/src/modals/ProjectNodeMatchModal/ProjectNodeMatchModal.stories.tsx, packages/ui/src/modals/ProjectNodeMatchModal/ProjectNodeMatchModal.test.tsx, packages/ui/src/modals/ProjectNodeMatchModal/ProjectNodeMatchModal.tsx, packages/ui/src/modals/ProjectNodeMatchModal/index.ts, packages/ui/src/modals/index.ts
stands up a basic find projects page for the nodes app
=> feat find projects page

apps/alpha/pages/fill-profile/index.tsx, apps/nodes/pages/create-project-fake/index.tsx, apps/nodes/pages/grants/index.tsx, apps/nodes/pages/launch/index.tsx, apps/nodes/pages/projects/index.tsx, packages/context/src/ProjectsContext/ProjectsContext.tsx, packages/context/src/ProjectsContext/ProjectsProvider.tsx, packages/context/src/ProjectsContext/index.ts, packages/context/src/index.ts, packages/graphql/generated/graphqlEden.ts, packages/ui/src/cards/WarningCard/WarningCard.tsx, packages/ui/src/cards/user/UserExperienceCard/UserExperienceCard.tsx, packages/ui/src/containers/CreateProjectTempContainer/CreateProjectTempContainer.tsx, packages/ui/src/containers/FillUserProfileContainer/FillUserProfileContainer.tsx, packages/ui/src/containers/ProjectsModalContainer/ProjectsModalContainer.stories.tsx, packages/ui/src/containers/ProjectsModalContainer/ProjectsModalContainer.test.tsx, packages/ui/src/containers/ProjectsModalContainer/ProjectsModalContainer.tsx, packages/ui/src/containers/ProjectsModalContainer/index.ts, packages/ui/src/containers/index.ts, packages/ui/src/modals/DiscoverTalentDropdownModal/DiscoverTalentDropdownModal.tsx, packages/ui/src/modals/RequirementsModal/RequirementsModal.tsx
this cleans up the basic context and state for the `/projects` page in the node app
=> nodes projects page basic logic

apps/grants/pages/grants/index.tsx, apps/nodes/pages/grants/index.tsx, apps/nodes/pages/projects/index.tsx, packages/context/src/GrantsContext/GrantsContext.tsx, packages/context/src/GrantsContext/GrantsProvider.tsx, packages/ui/src/components/SocialMediaComponent/SocialMediaComp.tsx, packages/ui/src/containers/GrantsModalContainer/GrantsModalContainer.tsx, packages/ui/src/containers/ViewUserProfileContainer/ViewUserProfileContainer.tsx, packages/ui/src/info/MemberInfo/MemberInfo.tsx
this cleans up grants context to only have what is being used.
also cleans up tracking for `currentUser`'s filled profile percentage on grants page
=> clean up grants context

apps/grants/pages/grants/index.tsx, apps/nodes/pages/grants/index.tsx, apps/nodes/pages/projects/index.tsx, packages/ui/src/cards/user/UserExperienceCard/UserExperienceCard.stories.tsx, packages/ui/src/cards/user/UserExperienceCard/UserExperienceCard.tsx, packages/ui/src/components/UserBackground/UserBackground.stories.tsx, packages/ui/src/containers/FillUserProfileContainer/FillUserProfileContainer.tsx, packages/ui/src/containers/ViewUserProfileContainer/ViewUserProfileContainer.stories.tsx, packages/ui/src/containers/ViewUserProfileContainer/ViewUserProfileContainer.tsx
this PR cleans up the grants and projects pages in the nodes app
replaced `any` types for graphql type
cleaned up state through out page flows
=> clean types and state, grants and projects pages

apps/nodes/pages/profile/index.tsx
this updates the edit `/profile` page on the nodes app
=> updated edit profile page

packages/ui/src/cards/OpenPositionCard/OpenPositionCard.tsx, packages/ui/src/components/OpenPositions/OpenPositions.tsx, packages/ui/src/info/ProjectNodeMatchInfo/ProjectNodeMatchInfo.tsx
This PR adds working apply by role for nodes app
Also comments out features that aren't supported by the backend yet: Refer and Project Timeline
=> working apply by role - nodes app

apps/alpha/pages/api/auth/[...nextauth].js, apps/nodes/pages/api/auth/[...nextauth].js, apps/web/pages/api/auth/[...nextauth].js
this key/value pair doesn't belong in the auth provider object.  this may have been causing issues for session
=> reduncency in the auth provider

apps/alpha/pages/champion-board/recruit/[_id].tsx
this PR updates the `champion-board/recruit` page in the alpha app to support the newer nodes api.
this change was missed with PR #759
=> update alpha recruit page

apps/alpha/pages/admin/create-party/index.tsx, apps/alpha/pages/party/host/[partyId].tsx, apps/alpha/pages/party/onboard/[partyId].tsx, apps/alpha/pages/profile/[handle]/index.tsx, apps/nodes/pages/onboard/admin-party/[partyId].tsx, apps/nodes/pages/onboard/party/[partyId].tsx, apps/web/pages/profile/[handle]/index.tsx, packages/graphql/eden/room/findRooms.ts, packages/graphql/generated/graphqlEden.ts, packages/ui/src/cards/OnboardRoomCard/OnboardRoomCard.tsx
This PR expands details of the onboarding room to include name, description, avatar, and hosts
=> expand party room data

apps/alpha/pages/discover/index.tsx, apps/alpha/pages/party/host/[partyId].tsx, apps/alpha/pages/party/onboard/[partyId].tsx, apps/nodes/pages/discover/index.tsx, packages/context/src/UserContext/UserContext.tsx, packages/context/src/UserContext/UserProvider.tsx, packages/ui/src/info/ProjectInfo/ProjectInfo.tsx
this PR adds to the UserContext an array of serverIDs called `memberServerIDs` for querying an array of server IDs
=> add memberServerID to UserContext

apps/alpha/pages/api/auth/fetchToken.ts, apps/web/pages/api/auth/fetchToken.ts, apps/web/pages/party/onboard/[partyId].tsx, packages/graphql/apollo-client.ts, packages/ui/src/cards/EditProfileOnboardPartyNodesCard/EditProfileOnboardPartyNodesCard.tsx, packages/ui/src/cards/user/UsersToMeetCard/UsersToMeetCard.tsx, packages/ui/src/containers/NodesOnboardPartyContainer/NodesOnboardPartyContainer.tsx
in `apollo-client.ts` change from axios to fetch
fixed error in `EditProfileOnboardPartyNodesCard` with `memberRole` value being null
=> fix: error with token request

apps/alpha/pages/create-project/index.tsx, apps/alpha/pages/test/create-project/index.tsx, packages/graphql/eden/index.ts, packages/graphql/eden/nodes/findNodes.ts, packages/graphql/eden/nodes/index.ts, packages/ui/src/cards/EditProfileOnboardPartyNodesCard/EditProfileOnboardPartyNodesCard.tsx, packages/ui/src/cards/user/UserCardOnboardPartyNodes/UserCardOnboardPartyNodes.tsx, packages/ui/src/info/MemberInfo/MemberInfo.tsx, packages/ui/src/lists/NodeList/NodeList.stories.tsx, packages/ui/src/lists/NodeList/NodeList.test.tsx, packages/ui/src/lists/NodeList/NodeList.tsx, packages/ui/src/lists/NodeList/index.ts, packages/ui/src/lists/index.ts, packages/ui/src/modals/DiscoverTalentDropdownModal/DiscoverTalentDropdownModal.tsx, packages/ui/src/modals/SelectNodesModal/SelectNodesModal.tsx
this PR adds the `NodeList` component
the node equivalent of the `SkillList` component
also creates a common `FIND_NODES` query
=> added NodeList

apps/alpha/pages/champion-board/recruit/[_id].tsx, packages/graphql/apollo-client.ts, packages/graphql/generated/graphqlEden.ts, packages/ui/src/cards/OpenPositionCard/OpenPositionCard.tsx, packages/ui/src/cards/project/ProjectEditSelectorCard/ProjectEditSelectorCard.tsx, packages/ui/src/components/OpenPositions/OpenPositions.tsx, packages/ui/src/containers/ChampionNodesMatchContainer/ChampionNodesMatchContainer.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectContainer.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews7/CreateProjectViews7.tsx, packages/ui/src/selectors/TabsSelector/TabsSelector.tsx
this PR uses the new `createProject` mutation with authorization 
also adds editing project
I will merge once fix in backend has been merged
=> feat: edit project

apps/alpha/pages/champion-board/recruit/[_id].tsx, apps/alpha/pages/discover/index.tsx, packages/graphql/eden/match/matchNodesToMembers.ts, packages/graphql/generated/graphqlEden.ts, packages/ui/src/modals/MemberModal/MemberModal.tsx, packages/ui/src/modals/UserInviteModal/UserInviteModal.tsx
making a request for the user in the `MemberModal` created a lot of extra requests
=> reduce requests

apps/alpha/pages/test/discover_test/index.tsx, packages/context/src/DiscoverContext/DiscoverProvider.tsx, packages/ui/package.json, packages/ui/src/components/DiscoverTalent/DiscoverTalent.tsx, packages/ui/src/components/DragDrop/DragDrop.stories.tsx, packages/ui/src/components/DragDrop/DragDrop.tsx, packages/ui/src/components/DragDrop/index.ts, packages/ui/src/components/index.ts, packages/ui/src/containers/DiscoverContainer/DiscoverContainer.tsx, yarn.lock
Research on Drag and Drop feature
=> Drag and drop Test done

apps/alpha/pages/champion-board/recruit/[_id].tsx, apps/alpha/pages/discover/index.tsx, packages/graphql/eden/currentUser/findCurrentUser.ts, packages/graphql/eden/currentUser/findCurrentUserSub.ts, packages/graphql/eden/project/findProject.ts, packages/ui/src/cards/project/ProjectEditSelectorCard/ProjectEditSelectorCard.tsx, packages/ui/src/components/SendMessageToUser/SendMessageToUser.tsx, packages/ui/src/selectors/ServerSelector/ServerSelector.stories.tsx, packages/ui/src/selectors/ServerSelector/ServerSelector.test.tsx, packages/ui/src/selectors/ServerSelector/ServerSelector.tsx, packages/ui/src/selectors/ServerSelector/index.ts, packages/ui/src/selectors/index.ts
this PR adds
- select server to send an invite to join project from champion
- a `ServerSelector` component to select a single server
=> server select for inviting members

apps/alpha/pages/champion-board/recruit/[_id].tsx, apps/alpha/pages/projects/index.tsx, apps/alpha/pages/test/create-project/index.tsx, packages/graphql/eden/project/matchNodesToProjectRoles.ts, packages/ui/src/components/OpenPositions/OpenPositions.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectContainer.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews2/CreateProjectViews2.tsx, packages/ui/src/containers/ViewProjectContainer/ViewProjectContainer.tsx, packages/ui/src/lists/ProjectChampionList/ProjectChampionList.tsx
error when updating a project a role was created twice
=> fix:error with updateProject

packages/ui/package.json, packages/ui/src/components/DragDrop/DragDrop.stories.tsx, packages/ui/src/components/DragDrop/DragDrop.tsx, packages/ui/src/containers/DiscoverContainer/DiscoverContainer.tsx
Added more designs to the drag and drop component
=> added more designs to the drag and drop component

packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews1/CreateProjectViews1.tsx, packages/ui/src/selectors/ServerSelectorMulti/ServerSelectorMulti.tsx
this PR adds allows a defaultValue to be passed into the component
=> fix: error with ServerSelectorMulti

packages/ui/src/components/DragDrop/DragDrop.tsx
Getting a new array every time a position of an item is changed in the array.
=> Returning new array for drag and drop

apps/alpha/pages/test/discover_test/index.tsx, packages/ui/src/components/DragDrop/DragDrop.tsx, packages/ui/src/containers/DiscoverContainer/DiscoverContainer.tsx, packages/ui/src/modals/TestDiscoverTalentDropdownModal/TestDiscoverTalentDropdownModal.stories.tsx, packages/ui/src/modals/TestDiscoverTalentDropdownModal/TestDiscoverTalentDropdownModal.test.tsx, packages/ui/src/modals/TestDiscoverTalentDropdownModal/TestDiscoverTalentDropdownModal.tsx, packages/ui/src/modals/TestDiscoverTalentDropdownModal/index.ts, packages/ui/src/modals/index.ts
Added a MODAL Intro to the discover test page and fixed some minor issues
=> Modal Intro View

apps/alpha/pages/projects/index.tsx, apps/web/pages/projects/index.tsx, packages/graphql/eden/match/matchNodesToMembers.ts, packages/ui/src/cards/project/ProjectNodeMatchCard/ProjectNodeMatchCard.tsx, packages/ui/src/cards/user/UserMiniCard/UserMiniCard.tsx, packages/ui/src/containers/NodesOnboardPartyContainer/NodesOnboardPartyContainer.tsx, packages/ui/src/info/ProjectNodeMatchInfo/ProjectNodeMatchInfo.tsx, packages/ui/src/modals/MemberModal/MemberModal.tsx
improved user details on expand
=> more details on user

packages/ui/src/cards/EndorsementCard/EndorsementCard.tsx, packages/ui/src/components/SendMessageToUser/SendMessageToUser.stories.tsx, packages/ui/src/components/SendMessageToUser/SendMessageToUser.tsx, packages/ui/src/modals/UserInviteModal/UserInviteModal.tsx, packages/ui/src/selectors/ServerSelector/ServerSelector.tsx
this PR adds a filter for the `ServerSelector` component
=> filter for serverselector

apps/alpha/pages/discover/index.tsx, packages/ui/src/cards/user/UserDiscoverCard/UserDiscoverCard.tsx, packages/ui/src/components/SendMessageToUser/SendMessageToUser.test.tsx, packages/ui/src/components/SendMessageUserToUser/SendMessageUserToUser.stories.tsx, packages/ui/src/components/SendMessageUserToUser/SendMessageUserToUser.test.tsx, packages/ui/src/components/SendMessageUserToUser/SendMessageUserToUser.tsx, packages/ui/src/components/SendMessageUserToUser/index.ts, packages/ui/src/components/index.ts, packages/ui/src/modals/UserMessageModal/UserMessageModal.stories.tsx, packages/ui/src/modals/UserMessageModal/UserMessageModal.test.tsx, packages/ui/src/modals/UserMessageModal/UserMessageModal.tsx, packages/ui/src/modals/UserMessageModal/index.ts, packages/ui/src/modals/index.ts
this PR adds user to user messaging
=> working user to user message

apps/alpha/pages/admin/error-log/index.tsx, apps/alpha/pages/api/auth/[...nextauth].ts, packages/graphql/apollo-client.ts, packages/graphql/generated/graphqlEden.ts
adding global error tracking
admin page for errors
=> added error logging

apps/alpha/pages/admin/error-log/index.tsx, apps/alpha/styles/global.css, apps/storybook/.storybook/global.css, apps/web/styles/global.css, packages/graphql/apollo-client.ts, packages/ui/package.json, packages/ui/src/-design/Typography.stories.tsx, packages/ui/src/atoms/text/TextInputLabel.tsx, packages/ui/src/atoms/text/index.ts, packages/ui/src/cards/project/ProjectEditSelectorCard/ProjectEditSelectorCard.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectContainer.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews1/CreateProjectViews1.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews2/CreateProjectViews2.test.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews2/CreateProjectViews2.tsx, packages/ui/src/elements/ToggleElement/ToggleElement.tsx, packages/ui/src/selectors/ServerSelectorMulti/ServerSelectorMulti.tsx, yarn.lock
this PR add the react-hook-form package
adding form to half of the `CreateProjectContainer`
the other half will come in another PR
=> add react-hook-form lib

packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews1/CreateProjectViews1.stories.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews2/CreateProjectViews2.stories.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews2/CreateProjectViews2.test.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews3/CreateProjectViews3.stories.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews3/CreateProjectViews3.test.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews3/CreateProjectViews3.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews4/CreateProjectViews4.stories.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews4/CreateProjectViews4.test.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews4/CreateProjectViews4.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews5/CreateProjectViews5.stories.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews5/CreateProjectViews5.test.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews5/CreateProjectViews5.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews6/CreateProjectViews6.stories.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews6/CreateProjectViews6.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews7/CreateProjectViews7.stories.tsx
this PR is a quick clean up of tests and storybook for all the used and unused components in this flow
=> clean up CreateProject

apps/alpha/pages/admin/create-party/index.tsx, apps/alpha/pages/admin/error-log/index.tsx, apps/alpha/pages/admin/index.tsx, packages/ui/src/layout/AdminLayout/AdminLayout.stories.tsx, packages/ui/src/layout/AdminLayout/AdminLayout.test.tsx, packages/ui/src/layout/AdminLayout/AdminLayout.tsx, packages/ui/src/layout/AdminLayout/index.ts, packages/ui/src/layout/AppPublicLayout/AppPublicLayout.tsx, packages/ui/src/layout/AppUserLayout/AppUserLayout.tsx, packages/ui/src/layout/index.ts
this PR cleans up layouts.
- `Head` and title items are handled on the page level through the `SEO` component
- `AdminLayout` for navigation through admin pages
- auth gated admin pages
=> cleanup layouts

packages/ui/src/components/DiscoverTalent/DiscoverTalent.stories.tsx, packages/ui/src/components/FillSocialLinks/FillSocialLinks.stories.tsx, packages/ui/src/components/FillSocialLinks/FillSocialLinks.test.tsx, packages/ui/src/components/FillSocialLinks/FillSocialLinks.tsx, packages/ui/src/components/FillSocialLinks/index.ts, packages/ui/src/components/ReportBugButton/ReportBugButton.tsx, packages/ui/src/containers/CreateProjectContainer/CreateProjectViews/CreateProjectViews7/CreateProjectViews7.tsx, packages/ui/src/layout/AdminLayout/AdminLayout.tsx
this PR fixes the error when initial project creation.
I wasn't paying attention and included other small changes and a new component `FillSocialLinks` which is a work in progress
=> fix error on initial create project

packages/mock/src/typeMocks/LinkTypeMock.ts, packages/ui/src/components/FillSocialLinks/FillSocialLinks.tsx, packages/ui/src/components/index.ts, packages/ui/src/containers/FillUserProfileContainer/FillUserProfileContainer.tsx
this PR replaces how the user adds links to their profile in the `FillUserProfileContainter` by using the `FillSocialLinks` component.  This component handles user input better for filtering out base urls
=> fix: error with links on FillUserProfileContainer

packages/ui/src/cards/EditProfileOnboardPartyNodesCard/EditProfileOnboardPartyNodesCard.tsx, packages/ui/src/components/FillSocialLinks/FillSocialLinks.tsx, packages/ui/src/components/SocialMediaComponent/SocialMediaComp.tsx
this PR adds `FillSocialLinks` component to the `EditProfileOnboardPartyNodesCard` to reduce code and use a common component for changing socials
=> add FillSocialLinks to EditProfileOnbardPartyNodes

apps/alpha/pages/test/discover_test/index.tsx, packages/ui/src/cards/user/UserDiscoverCardTest/UserDiscoverCardTest.stories.tsx, packages/ui/src/cards/user/UserDiscoverCardTest/UserDiscoverCardTest.test.tsx, packages/ui/src/cards/user/UserDiscoverCardTest/UserDiscoverCardTest.tsx, packages/ui/src/cards/user/UserDiscoverCardTest/index.ts, packages/ui/src/cards/user/index.ts, packages/ui/src/components/DragDrop/Column.tsx, packages/ui/src/components/DragDrop/DragDrop.tsx, packages/ui/src/lists/CommonServerAvatarListTest/CommonServerAvatarListTest.stories.tsx, packages/ui/src/lists/CommonServerAvatarListTest/CommonServerAvatarListTest.test.tsx, packages/ui/src/lists/CommonServerAvatarListTest/CommonServerAvatarListTest.tsx, packages/ui/src/lists/CommonServerAvatarListTest/index.ts, packages/ui/src/lists/index.ts
=> User Card iteration

apps/alpha/pages/champion-board/recruit/[_id].tsx, packages/ui/src/cards/project/ProjectNodeMatchCard/ProjectNodeMatchCard.tsx
this PR fixes an error I made last PR where I removed the `useEffect` needed to populate the create project flow with an existing project for updating
=> fix: error updateProject

packages/ui/src/components/OpenPositions/OpenPositions.tsx, packages/ui/src/components/SendMessageToChampion/SendMessageToChampion.tsx, packages/ui/src/components/SendMessageToUser/SendMessageToUser.tsx, packages/ui/src/modals/UserInviteModal/UserInviteModal.tsx
this PR aligns to the backend to properly allow proper auth by user to perform this mutation
=> changeTeamMemberPhaseProject auth

packages/ui/src/archive/containers/SignUpContainer/SignUpContainer.tsx, packages/ui/src/archive/modals/ApplyByRoleModal/ApplyByRoleModal.tsx, packages/ui/src/containers/FillUserProfileContainer/FillUserProfileContainer.tsx
don't merge this PR until Blue merges PR (213) on the backend
=> updateMember auth

packages/ui/src/archive/modals/ApplyByRoleModal/ApplyByRoleModal.tsx, packages/ui/src/components/OpenPositions/OpenPositions.tsx, packages/ui/src/components/SendMessageToChampion/SendMessageToChampion.tsx, packages/ui/src/elements/Button/Button.tsx
this PR adds to apply by role discord messaging
=> apply to role

packages/context/src/DiscoverContext/DiscoverContext.tsx, packages/context/src/GrantsContext/GrantsContext.tsx, packages/context/src/ProjectsContext/ProjectsContext.tsx, packages/ui/src/containers/DiscoverContainer/DiscoverContainer.tsx
removed eslint errors in contexts
=> eslint errors in context

apps/alpha/pages/grants/[id]/index.tsx
testing base url for local and production deployments
=> test baseUrl

apps/storybook/.storybook/main.ts, packages/ui/g6/GraphVisualisation/GraphVisualisation.stories.tsx, packages/ui/g6/GraphVisualisation/GraphVisualisation.tsx
adding the g6 folder to render on storybook
=> g6 components on storybook

packages/ui/src/components/SendMessageToChampion/SendMessageToChampion.tsx
this fixes the error with messaging a champion of a project.
if no `threadId` exists in the server information then a message can not be sent
=> fix for message to champion

apps/alpha/pages/discover/index.tsx, packages/ui/src/cards/WarningCard/WarningCard.tsx
this PR add server selection to discover page
=> server select for discover page

apps/alpha/pages/admin/grants/index.tsx, packages/ui/src/layout/AdminLayout/AdminLayout.tsx, packages/ui/src/selectors/ServerSelector/ServerSelector.tsx
ability to create grant for admins
=> feat: create grant admin page

apps/alpha/constants.ts, apps/alpha/pages/api/discord/createForumPost.ts, apps/alpha/pages/chat/index.tsx, apps/alpha/types/type.ts, packages/ui/src/components/SendMessageToChampion/SendMessageToChampion.tsx, packages/ui/src/components/SendMessageToUser/SendMessageToUser.tsx, packages/ui/src/components/SendMessageUserToUser/SendMessageUserToUser.tsx, packages/ui/types/type.ts
- Add button support in api `createForumPost`, after I researched again.(Sorry for my previous conclusion, lol)
- Change the order of mentions when you create post with these three tags -- `Project Application`, `Project Interest` and `User Introduction`
=> feat: add buttons

apps/alpha/pages/grants/index.tsx, apps/web/pages/grants/index.tsx, packages/ui/src/containers/FillUserProfileContainer/FillUserProfileContainer.tsx, packages/ui/src/containers/GrantsModalContainer/GrantsModalContainer.tsx
this PR removes the last use of the `addNodesToMember` mutation from the frontend
=> change update nodes on grants page

apps/alpha/pages/_app.tsx, apps/alpha/pages/admin/party-rooms/index.tsx, apps/alpha/pages/party/onboard/[partyId].tsx, apps/web/pages/_app.tsx, apps/web/pages/party/onboard/[partyId].tsx, packages/ui/src/cards/OnboardRoomCard/OnboardRoomCard.tsx
this PR updates the party page
- moves info for page to SSR for SEO
- reduce # of queries for `enterRoom`
- adds host and host info to `OnboardRoomCard`
=> update party page

packages/graphql/eden/codegen.yml, packages/graphql/eden/currentUser/findCurrentUser.ts, packages/graphql/eden/currentUser/findCurrentUserSub.ts, packages/graphql/eden/member/findMember.ts, packages/graphql/eden/member/findMemberInfo.ts, packages/graphql/eden/member/findMembers.ts, packages/graphql/eden/project/findProject.ts, packages/graphql/generated/graphqlEden.ts, packages/mock/src/graphqlMocks/MembersMock.ts, packages/mock/src/typeMocks/PreviousProjectsTypeMock.ts, packages/mock/src/typeMocks/RoleTypeMock.ts, packages/mock/src/typeMocks/index.ts, packages/ui/src/archive/cards/RoleCard/RoleCard.tsx, packages/ui/src/archive/cards/user/UserInformationCard/UserInformationCard.stories.tsx, packages/ui/src/archive/cards/user/UserInformationCard/UserInformationCard.tsx, packages/ui/src/cards/user/UserExperienceCard/UserExperienceCard.stories.tsx, packages/ui/src/cards/user/UserExperienceCard/UserExperienceCard.tsx, packages/ui/src/components/UserBackground/UserBackground.stories.tsx, packages/ui/src/components/UserBackground/UserBackground.tsx, packages/ui/src/containers/FillUserProfileContainer/FillUserProfileContainer.tsx, packages/ui/src/containers/ViewUserProfileContainer/ViewUserProfileContainer.tsx, packages/ui/src/info/MemberInfo/MemberInfo.tsx, packages/ui/src/info/MemberInfoWithGraph/MemberInfoWithGraph.tsx, packages/ui/src/modals/ApplicationModal/ApplicationModal.tsx, packages/ui/src/modals/RoleDescriptionModal/RoleDescriptionModal.tsx, packages/ui/utils/fill-profile-percentage.tsx
this PR fixes the spelling errors in schema and type matching
=> fix schema spelling

apps/alpha/pages/api/auth/[...nextauth].ts, apps/web/pages/api/auth/[...nextauth].ts, package.json
this PR handles error better for no server
=> bug: better error handling for no server

packages/ui/src/flows/EndorsementFlow/EndorsementFlow.tsx, packages/ui/src/flows/EndorsementFlow/components/ChatBox.tsx, packages/ui/src/flows/EndorsementFlow/components/EndorsementMemberContainer.tsx, packages/ui/src/flows/EndorsementFlow/components/EndorsementModalView1.tsx, packages/ui/src/flows/EndorsementFlow/components/EndorsementModalView2.tsx, packages/ui/src/flows/EndorsementFlow/components/StarRating.tsx
this PR cleans up some of the ui/ux in the `EndorsementFlow`
=> clean up endorsement ui/ux

apps/alpha/pages/test/cv_gpt_all/index.tsx, apps/alpha/pages/test/cv_jobs/index.tsx
The `HolisticCvGPT` component is designed to process a user-uploaded PDF resume and extract useful information, such as a CV summary, job summaries, and relevant skills. It then displays this information in a visually appealing and easy-to-read format.
- File upload input to select a PDF resume.
- Loading state to indicate the progress of the resume processing.
- Display of the extracted CV summary in a bulleted list.
- Display of the extracted job summaries in a nested bulleted list.
- Display of the relevant skills using the `DynamicSearchGraph` component.
- `@apollo/client`: for GraphQL queries and mutations.
- `@eden/package-ui`: for the `Button` and `DynamicSearchGraph` components.
- `react`: for defining and rendering the React component.
- `CV_TO_SUMMARY`: A GraphQL mutation that …
=> Holistic component for CV GPT  

apps/alpha/pages/test/flow/endorsement/[id].tsx
removes a check for localhost to run script.  for some reason, hotjar wasn't detecting this page after adding this in.
=> remove detect localhost

apps/web/pages/create-profile/index.tsx, apps/web/pages/discover/index.tsx
this PR adds the hotjar script to discover and create-profile pages on the web app
=> add hotjar to discover and create-profile

apps/web/pages/create-profile/index.tsx
`if (!currentUser) return null;` was causing the hotjar script not to load
=> fix hotjar script error

apps/alpha/pages/test/ExpirienceCreateProfileChat/index.tsx, apps/alpha/pages/test/ExpirienceCreateProfileChatCV/index.tsx, packages/ui/src/components/EdenAiChat/EdenAiChat.tsx, packages/ui/src/components/EdenAiChat/gqlFunctions.tsx
In this version of the ai chat, it takes the CV and the questions are being asked with the context of information that was extracted from that CV.
=> AI chat w/ resume 

apps/saas/pages/companyCRM/[companyID].tsx, packages/ui/src/lists/CandidatesTableList/CandidatesTableList.tsx
- fixed some typescript errors that were breaking the conditional rendering of the data.
updated image:
with the selected candidate modal working:
=> fix: typescript errors in rendering table data

packages/ui/src/lists/CandidatesTableList/CandidatesTableList.tsx
- arranged column size for background
- arranged size and text colors for score and rate per hour columns
=> feat: arranged column size and text colors

apps/saas/pages/dashboard/[companyID].tsx, packages/graphql/eden/company/findCompanyCandidates.ts, packages/graphql/eden/company/findCompanyFull.ts, packages/graphql/eden/company/findCompanyQuestionsToAsk.ts, packages/graphql/eden/company/index.ts, packages/graphql/eden/fragments/companyCandidatesFragment.ts, packages/graphql/eden/index.ts, packages/ui/src/charts/BackgroundMatchChart/BackgroundMatchChart.tsx, packages/ui/src/info/CandidateInfo/CandidateInfo.tsx, packages/ui/src/info/CandidateInfo/tabs/InfoTab.tsx, packages/ui/src/info/CandidateInfo/tabs/MatchTab.tsx, packages/ui/src/layout/AppUserLayout/AppUserLayout.tsx, packages/ui/src/lists/CandidatesTableList/CandidatesTableList.tsx, packages/ui/src/modals/CandidateModal/CandidateModal.tsx
- divided the dashboard in two columns
- added graphql queries in graphql package
- tried to implement graphql fragments
- removed unnused code
- set selected candidate row background color
image preview:
next:
- fix discord avatar when Candidate row is selected
- search filter bar
- filters & sort ?
- favorite icon
- resize the background match bar chart
=> feat: new 2 columns page layout checkpoint

apps/saas/pages/dashboard/[companyID].tsx, packages/graphql/eden/company/createNewTalentList.ts, packages/graphql/eden/company/index.ts, packages/graphql/eden/company/updateTalentListWithTalent.ts, packages/ui/src/lists/CandidatesTableList/CandidatesTableList.tsx
- new talent list creation working
- after creation, talent selected is updated to it
=> feat: talent lists checkpoint 02

apps/saas/pages/dashboard/[companyID].tsx, packages/ui/src/lists/CandidatesTableList/CandidatesTableList.tsx
- edit mode to talentLists feature
=> feat: edit mode to talentLists feature

packages/ui/src/info/CandidateInfo/tabs/InfoTab.tsx
=> Only the top 3 skills are now showing

apps/saas/pages/dashboard/[positionID].tsx, packages/ui/package.json, packages/ui/src/elements/SelectList/SelectList.tsx, yarn.lock
- bugfix related about showing the correct talentlist after edition 
- uninstalled unnused dependency
=> feat: bugfixing on talent list edition

apps/saas/pages/dashboard/[positionID].tsx
showing talistlists statuts with react-toastify
=> feat: creation/edition notifications

apps/saas/pages/dashboard/[...params].tsx, packages/graphql/eden/index.ts, packages/graphql/eden/talentlist/findTalentList.ts, packages/graphql/eden/talentlist/index.ts
sharing talent list working and showing it reading from the URL **if available**
=> feat: share talent list button

packages/ui/src/components/UserBackground/UserBackground.tsx, packages/ui/src/info/CandidateInfo/tabs/InfoTab.tsx
=> Better jobs formatting

packages/ui/src/lists/CandidatesTableList/CandidatesTableList.tsx
=> Bug/fix uneven table and get rid of undefined 

packages/ui/src/info/CandidateInfo/tabs/ReportNotes.tsx
=> Improved hover

apps/saas/pages/dashboard/[...params].tsx, apps/saas/pages/dashboard/[positionID].tsx, packages/ui/src/components/TrainQuestionsEdenAI/TrainQuestionsEdenAI.tsx, packages/ui/src/info/CandidateInfo/CandidateInfo.tsx
approve and reject buttons working, lacks of some details **to be defined**
Linear comment with questions: https://linear.app/eden-protocol/issue/TALD-130#comment-7028076c
=> feat: approve and reject buttons first checkpoint

apps/saas/pages/dashboard/[positionID].tsx
fix: validation on empty approved/rejected talent lists without candidates
=> fix: validation on empty approved/rejected talent lists without candidates

apps/saas/pages/dashboard/[positionID].tsx
- added missed validation when there is no candidates rejected or accepted on those talent lists
=> fix: added missed validation

apps/saas/pages/dashboard/[positionID].tsx
New list creation with the name of new list required
=> feat: New list creation with the name of new list required

packages/ui/src/info/CandidateInfo/tabs/ReportNotes.tsx
- fixed category average letter grade with new popover
=> feat: fixed category average letter grade with new popover

apps/saas/pages/[slug]/jobs/index.tsx, apps/saas/pages/redirect-page/post-job.tsx, apps/saas/pages/request-access/index.tsx, packages/ui/src/components/LeftToggleNav/LeftToggleNav.tsx
Reverts Soil-labs/eden-app-2-FrontEnd#1757
=> Revert "Revert "Some fixes 🤘 ""
